<h2>Vision</h2>

<p>
ACE brings the idea of real-time cooperative editing into concrete implementation. Real-time cooperative editing systems allow multiple geographically dispersed users to view and edit a shared document at the same time. 
</p>
<p>
ACE is a plattform-independent and collaborative editor for creating simple text documents. Yet it is one implementation of a simple document model, so to speak the starting shot in the realization of an emerging research area, namely CSCW or more specific groupware. The vision behind ACE provides for more. What if software would allow people to collaboratively edit advanced text processing documents, create a presentation, edit a graphics document or write software in a useful manner? We believe there are a lot more potential application areas for groupware systems, most of which we don't even think about. The idea of a real-time cooperative editing system creates a totally new way of using the computer whereas most people have no clue that it exists.<br>
This limitation of todays state-of-the-art systems builds the foundation for the vision behind ACE. ACE shall enforce and motivate open source developers to start writing collaborative software and to enter with it a new area of using computers where we haven't been yet. The potential impact could be immense. Let's launch into this great challenge! <br>
Furthermore, the benefit of ACE shall not be confined to technically versed people but also and mainly to average computer users. The vision is to write collaborative software which can be adopted in such a simple way that people start integrate it in their daily work. ACE is aimed to be such an editor.
</p>
<p>
ACE focuses on an open architecture design. ACE accounts for a best possible interchangeability of editor components such as document models, GUI's, operational transformation (OT) algorithms and network service. For example, one could use ACE to design a collaborative graphics editor using a document model, a GUI and an algorithm with transformation functions for graphics. Furthermore, the interface to the network layer shall be designed in such a way that ACE is independent of the network service as far as possible. This lets a developer experiment with different component implementations in a free and independent manner. <br>
The architecture of ACE gives the developer complete freedom over the way he wants to assemble his collaborative editing system. Therefore, ACE is not only the first open source plattform-independent collaborative text editor, it shall become the foundation for many other collaborating editing systems.
</p>